name: Docker Compose Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner
    env:
      VM_IP: ${{ secrets.VM_IP }}
      AITOKEN: ${{ secrets.CLARETOKEN }}
      MONGOURL: ${{ secrets.MONGOURL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Log secrets
        run: |
          echo "VM_IP: $VM_IP"
          echo "AITOKEN: $AITOKEN"
          echo "MONGOURL: $MONGOURL"

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
